DROP TABLE PARTICIPANT_AVOCAT;
DROP TABLE PARTICIPANT_CAZ;
DROP TABLE JUDECATOR_CAZ;
DROP TABLE PROCUROR_CAZ;
DROP TABLE MARTOR_CAZ;
DROP TABLE PERSOANA_FIZICA;
DROP TABLE PERSOANA_JURIDICA;
DROP TABLE CAZ;
DROP TABLE MARTOR;
DROP TABLE JUDECATOR;
DROP TABLE AVOCAT;
DROP TABLE TRIBUNAL;
DROP TABLE PROCUROR;
DROP TABLE PARTICIPANT;

CREATE TABLE JUDECATOR (
    ID_JUDECATOR NUMBER(5) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_JUDECATOR PRIMARY KEY ,
    NUME VARCHAR2(20) NOT NULL,
    PRENUME VARCHAR2(30) DEFAULT '-',
    SPECIALIZARE VARCHAR2(20) DEFAULT '-',
    TELEFON VARCHAR2(20) DEFAULT '-' CONSTRAINT CH_TELEFON_JUDECATOR CHECK(TELEFON LIKE '07%' or TELEFON = '-'),
    SALARIU NUMBER(6) CONSTRAINT CH_SALARIU_JUDECATOR CHECK (SALARIU>0) NOT NULL
);

CREATE TABLE TRIBUNAL (
    ID_TRIBUNAL NUMBER(5) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_TRIBUNAL PRIMARY KEY,
    NUME VARCHAR2(50) NOT NULL UNIQUE,
    JUDET VARCHAR2(20) NOT NULL,
    NR_SALI NUMBER(3),
    WEBSITE VARCHAR2(50) DEFAULT '-' CONSTRAINT CH_WEBSITE_TRIBUNAL CHECK(WEBSITE LIKE 'WWW.%.%' or WEBSITE = '-'),
    TELEFON VARCHAR2(20) DEFAULT '-' CONSTRAINT CH_TELEFON_TRIBUNAL CHECK(TELEFON LIKE '07%' or TELEFON = '-')
);

CREATE TABLE AVOCAT(
    ID_AVOCAT NUMBER(5) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_AVOCAT PRIMARY KEY,
    NUME VARCHAR2(20) NOT NULL,
    PRENUME VARCHAR2(30) DEFAULT '-',
    SPECIALIZARE VARCHAR2(20) DEFAULT '-',
    TELEFON VARCHAR2(20) DEFAULT '-' CONSTRAINT CH_TELEFON_AVOCAT CHECK(TELEFON LIKE '07%' or TELEFON = '-'),
    JUDET VARCHAR2(20) DEFAULT '-'
);

CREATE TABLE PROCUROR(
    ID_PROCUROR NUMBER(5) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_PROCUROR PRIMARY KEY,
    NUME VARCHAR2(20) NOT NULL,
    PRENUME VARCHAR2(30) DEFAULT '-',
    SPECIALIZARE VARCHAR2(20) DEFAULT  '-',
    ACT_NUMIRE VARCHAR2(50) DEFAULT '-',
    STUDII VARCHAR2(50) DEFAULT '-'
);

CREATE TABLE MARTOR(
    ID_MARTOR NUMBER(5) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_MARTOR PRIMARY KEY,
    NUME VARCHAR2(20) NOT NULL,
    PRENUME VARCHAR2(30) DEFAULT '-',
    TELEFON VARCHAR2(20) DEFAULT '-' CONSTRAINT CH_TELEFON_MARTOR CHECK(TELEFON LIKE '07%' or TELEFON = '-'),
    PROFESIE VARCHAR2(20) DEFAULT '-'
);

CREATE TABLE CAZ(
    ID_CAZ NUMBER(5) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_CAZ PRIMARY KEY,
    ID_TRIBUNAL NUMBER(5) NOT NULL CONSTRAINT FK_TRIBUNAL REFERENCES TRIBUNAL(ID_TRIBUNAL) ON DELETE CASCADE ,
    TIP VARCHAR2(20),
    DATA_I DATE NOT NULL,
    DATA_F DATE,
    CONSTRAINT CH_DATE_CAZ CHECK (DATA_F > DATA_I)
);

CREATE TABLE PROCUROR_CAZ(
    ID_PROCUROR NUMBER(5),
    ID_CAZ NUMBER(5),
    PRIMARY KEY (ID_PROCUROR, ID_CAZ),
    FOREIGN KEY (ID_PROCUROR) REFERENCES PROCUROR(ID_PROCUROR) ON DELETE CASCADE ,
    FOREIGN KEY (ID_CAZ) REFERENCES CAZ(ID_CAZ) ON DELETE CASCADE ,
    FUNCTIE_PROCUROR VARCHAR2(30) DEFAULT '-'
);

CREATE TABLE JUDECATOR_CAZ(
    ID_JUDECATOR NUMBER(5),
    ID_CAZ NUMBER(5),
    PRIMARY KEY (ID_JUDECATOR, ID_CAZ),
    FOREIGN KEY (ID_JUDECATOR) REFERENCES JUDECATOR(ID_JUDECATOR) ON DELETE CASCADE ,
    FOREIGN KEY (ID_CAZ) REFERENCES CAZ(ID_CAZ) ON DELETE CASCADE ,
    FUNCTIE_JUDECATOR VARCHAR2(30) DEFAULT '-'
);

CREATE TABLE MARTOR_CAZ(
    ID_MARTOR NUMBER(5),
    ID_CAZ NUMBER(5),
    PRIMARY KEY (ID_MARTOR, ID_CAZ),
    FOREIGN KEY (ID_MARTOR) REFERENCES MARTOR(ID_MARTOR) ON DELETE CASCADE ,
    FOREIGN KEY (ID_CAZ) REFERENCES CAZ(ID_CAZ) ON DELETE CASCADE ,
    PROTECTIE_MARTOR VARCHAR2(3) CONSTRAINT CHECK_PROTECTIE_MARTOR CHECK (PROTECTIE_MARTOR IN ('DA', 'NU')),
    TIP_CITATIE VARCHAR2(20) CONSTRAINT CHECK_CITATIE_MARTOR CHECK (TIP_CITATIE IN ('Fizic', 'Telefonic', 'Electronic'))
);

CREATE TABLE PARTICIPANT(
    ID_PARTICIPANT NUMBER(5) GENERATED ALWAYS AS IDENTITY CONSTRAINT PK_PARTICIPANT PRIMARY KEY,
    NUME VARCHAR2(50) DEFAULT '-'
);

CREATE TABLE PERSOANA_FIZICA(
    ID_PARTICIPANT NUMBER(5) PRIMARY KEY,
    NATIONALITATE VARCHAR2(20) DEFAULT '-',
    TELEFON VARCHAR2(20) DEFAULT '-' CONSTRAINT CH_TELEFON_PARTICIPANT CHECK(TELEFON LIKE '07%' or TELEFON = '-'),
    PROFESIE VARCHAR2(20) DEFAULT '-',
    ADRESA VARCHAR2(50) DEFAULT '-',
    CONSTRAINT FK_PFIZICA FOREIGN KEY (ID_PARTICIPANT) REFERENCES PARTICIPANT(ID_PARTICIPANT) ON DELETE CASCADE
);

CREATE TABLE PERSOANA_JURIDICA(
    ID_PARTICIPANT NUMBER(5) PRIMARY KEY,
    TIP_FIRMA VARCHAR(10) DEFAULT 'Other' CONSTRAINT CH_TIP_PJURIDICA CHECK (TIP_FIRMA IN ('ONG', 'SRL', 'SA', 'PFA', 'Other')),
    CUI VARCHAR2(10) UNIQUE NOT NULL,
    DOMENIU_ACTIVITATE VARCHAR2(30) DEFAULT '-',
    EMAIL VARCHAR2(30) DEFAULT '-' CONSTRAINT CH_EMAIL_PJURIDICA CHECK(EMAIL LIKE '%@%.%' OR EMAIL = '-'),
    CONSTRAINT FK_PJURIDICA FOREIGN KEY (ID_PARTICIPANT) REFERENCES PARTICIPANT(ID_PARTICIPANT) ON DELETE CASCADE
);


CREATE TABLE PARTICIPANT_AVOCAT(
    ID_PARTICIPANT NUMBER(5),
    ID_AVOCAT NUMBER(5),
    PRIMARY KEY (ID_PARTICIPANT, ID_AVOCAT),
    FOREIGN KEY (ID_PARTICIPANT) REFERENCES PARTICIPANT(ID_PARTICIPANT) ON DELETE CASCADE ,
    FOREIGN KEY (ID_AVOCAT) REFERENCES AVOCAT(ID_AVOCAT) ON DELETE CASCADE ,
    TIP_AVOCAT VARCHAR2(10) NOT NULL CONSTRAINT CHECK_TIP_AVOCAT CHECK (TIP_AVOCAT IN ('Oficiu', 'Ales')),
    ONORARIUL NUMBER(7) CONSTRAINT CH_ONORARIUL_AVOCAT CHECK (ONORARIUL>0)
);

CREATE TABLE PARTICIPANT_CAZ (
    ID_PARTICIPANT NUMBER(5),
    ID_CAZ NUMBER(5),
    PRIMARY KEY (ID_PARTICIPANT, ID_CAZ),
    FOREIGN KEY (ID_PARTICIPANT) REFERENCES PARTICIPANT(ID_PARTICIPANT) ON DELETE CASCADE ,
    FOREIGN KEY (ID_CAZ) REFERENCES CAZ(ID_CAZ) ON DELETE CASCADE ,
    PARTE VARCHAR2(20) NOT NULL CONSTRAINT CHECK_TIP_PARTICIPANT CHECK (PARTE IN ('Suspect', 'Persoana Vatamata'))
);

INSERT INTO TRIBUNAL (NUME, JUDET, NR_SALI, WEBSITE, TELEFON)
VALUES ('Tribunalul Arges', 'Arges', 5, 'WWW.tribunalarges.ro', '0734567890');

INSERT INTO TRIBUNAL (NUME, JUDET, NR_SALI, WEBSITE, TELEFON)
VALUES ('Tribunalul Bucuresti', 'Bucuresti', 10, 'WWW.tribunalbucuresti.ro', '0723456789');

INSERT INTO TRIBUNAL (NUME, JUDET, NR_SALI, WEBSITE, TELEFON)
VALUES ('Tribunalul Cluj', 'Cluj', 8, 'WWW.tribunalcluj.ro', '0745123456');

INSERT INTO TRIBUNAL (NUME, JUDET, NR_SALI, WEBSITE, TELEFON)
VALUES ('Tribunalul Sibiu', 'Sibiu', 6, 'WWW.tribunalsibiu.ro', '0767890123');

INSERT INTO TRIBUNAL (NUME, JUDET, NR_SALI, WEBSITE, TELEFON)
VALUES ('Tribunalul Timis', 'Timis', 7, 'WWW.tribunaltimis.ro', '0756432109');


INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Popescu', 'Ion', 'Penal', '0723456789', 9000);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Popescu', 'Maria', 'Penal', '0797656789', 10000);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Minulescu', 'Mariu', 'Penal', '0733420579', 11500);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Dimitrie', 'Andrei', 'Penal', '0760400849', 10500);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Lupascu', 'Ion', 'Civil', '0703422389', 12500);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Tunariu', 'Cornel', 'Civil', '0703002339', 14500);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Zegreanu', 'Mihai', 'Civil', '0753421389', 12500);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Mocanu', 'Dani', 'Administrativ', '07104202389', 11500);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Jurca', 'Simona', 'Administrativ', '0711221350', 10000);

INSERT INTO JUDECATOR (NUME, PRENUME, SPECIALIZARE, TELEFON, SALARIU)
VALUES ('Istrate', 'Filip', 'Administrativ', '0769401122', 12000);


INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Visinescu', 'Mihai', 'Penal', 'Decretul Presedintelui','Facultatea de Drept Bucuresti');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Antonescu', 'George', 'Penal', 'Decretul Presedintelui','Facultatea de Drept Iasi');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Costescu', 'Daria', 'Penal', 'Hotarare CSM','Facultatea de Drept Bucuresti');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Chiriac', 'Cristina', 'Civil', 'Decretul Presedintelui','Facultatea de Drept Bucuresti');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Coman', 'Marius', 'Civil', 'Decretul Presedintelui','Facultatea de Drept Cluj');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Georgescu', 'Maria', 'Administrativ', 'Hotarare CSM','Facultatea de Drept Bucuresti');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Enache', 'Alexandru', 'Administrativ', 'Decretul Presedintelui','Facultatea de Drept Bucuresti');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Enescu', 'Andrei', 'Administrativ', 'Decretul Presedintelui','Facultatea de Drept Bucuresti');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Dumitru', 'Theodor', 'Financiar', 'Decretul Presedintelui','Facultatea de Drept Bucuresti');

INSERT INTO PROCUROR (NUME, PRENUME, SPECIALIZARE, ACT_NUMIRE, STUDII)
VALUES ('Albu', 'Horia', 'Financiar', 'Hotarare CSM','Facultatea de Drept Iasi');


INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Popescu', 'Ion', '0723456789', 'Medic');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Ionescu', 'Maria', '0744567890', 'Profesor');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Dumitru', 'Andrei', '0732123456', 'Inginer');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Vasilescu', 'Ana', '0765432109', 'Avocat');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Marinescu', 'George', '0721987654', 'Contabil');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Tudor', 'Elena', '0734987654', 'Jurnalist');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Mihai', 'Florin', '0745123987', 'Arhitect');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Stan', 'Cristina', '0756789012', 'Psiholog');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Radu', 'Alexandru', '0771234567', 'Politist');

INSERT INTO MARTOR (NUME, PRENUME, TELEFON, PROFESIE)
VALUES ('Georgescu', 'Ioana', '0789876543', 'Farmacist');


INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Balan', 'Sebastian', 'Civil', '0721345678', 'Arges');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Babus', 'Ion', 'Civil', '0700123678', 'Bucuresti');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Brancoveanu', 'Maria', 'Civil', '0700745121', 'Arges');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Zidaru', 'George', 'Penal', '0766125098', 'Cluj');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Neagoe', 'Alexandru', 'Penal', '0712340422', 'Cluj');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Harlet', 'Mihai', 'Penal', '0700240182', 'Bucuresti');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Jupanu', 'Elena', 'Administrativ', '0710090222', 'Bucuresti');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Lopataru', 'Denisa', 'Financiar', '0795341230', 'Sibiu');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Lavanda', 'Sidonia', 'Financiar', '072224792', 'Sibiu');

INSERT INTO AVOCAT (NUME, PRENUME, SPECIALIZARE, TELEFON, JUDET)
VALUES ('Visan', 'Sorin', 'Financiar', '0712311202', 'Timis');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Stancu Ion');
INSERT INTO PERSOANA_FIZICA(ID_PARTICIPANT, NATIONALITATE, TELEFON, PROFESIE, ADRESA)
VALUES(1,'Romania','0770248034', 'Inginer', 'Bucuresti Strada Cernisoara 31');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Pop Maria');
INSERT INTO PERSOANA_FIZICA(ID_PARTICIPANT, NATIONALITATE, TELEFON, PROFESIE, ADRESA)
VALUES(2,'Romania','0734248077', 'Muzician', 'Bucuresti Strada Lavandei 22');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Frederique Constantin');
INSERT INTO PERSOANA_FIZICA(ID_PARTICIPANT, NATIONALITATE, TELEFON, PROFESIE, ADRESA)
VALUES(3,'Franta','', 'Pictor', 'Iasi Strada Eminescu 22');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Zidaru Cosmin');
INSERT INTO PERSOANA_FIZICA(ID_PARTICIPANT, NATIONALITATE, TELEFON, PROFESIE, ADRESA)
VALUES(4,'Romania','0770248884', 'Profesor', 'Bucuresti Strada Sanzienelor 41');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Dumitrescu Maria');
INSERT INTO PERSOANA_FIZICA(ID_PARTICIPANT, NATIONALITATE, TELEFON, PROFESIE, ADRESA)
VALUES(5,'Romania','0723048224', 'Doctor', 'Timisoara Strada Apusului 3');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Jinga Maria');
INSERT INTO PERSOANA_FIZICA(ID_PARTICIPANT, NATIONALITATE, TELEFON, PROFESIE, ADRESA)
VALUES(6,'Romania','0777001243', 'Arhitect', 'Timisoara Strada Rasaritului 3');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Ianos Virgil');
INSERT INTO PERSOANA_FIZICA(ID_PARTICIPANT, NATIONALITATE, TELEFON, PROFESIE, ADRESA)
VALUES(7,'Ungaria','0768248195', 'Profesor', 'Ungaria Budapesta 1012');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Fabrica de Arta SRL');
INSERT INTO PERSOANA_JURIDICA(ID_PARTICIPANT, TIP_FIRMA, CUI, DOMENIU_ACTIVITATE, EMAIL)
VALUES (8, 'SRL','0981236574', 'Design', 'fabricaDeArta@gmail.com');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Smart Tech');
INSERT INTO PERSOANA_JURIDICA(ID_PARTICIPANT, TIP_FIRMA, CUI, DOMENIU_ACTIVITATE, EMAIL)
VALUES (9, 'SA','0944231274', 'Technologie', 'officialConstructio@gmail.com');

INSERT INTO PARTICIPANT(NUME)
VALUES ('Salvati Copiii');
INSERT INTO PERSOANA_JURIDICA(ID_PARTICIPANT, TIP_FIRMA, CUI, DOMENIU_ACTIVITATE, EMAIL)
VALUES (10, 'ONG','0111223562', 'Auto', 'officialBMW@gmail.com');


INSERT INTO CAZ (ID_TRIBUNAL, TIP, DATA_I, DATA_F)
VALUES (2,'Penal', date '2005-01-12',date '2007-01-05');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (1,1, 'Persoana Vatamata');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (2,1, 'Suspect');

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT)
VALUES (1,2, 'Oficiu');

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (2,10, 'Ales',10000);

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (1,1,'Presedinte');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (9,1,'Membru');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (8,1,'Membru');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (1,1,'Presedinte Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (2,1,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (6,1,'Membru Complet');

INSERT INTO MARTOR_CAZ (ID_MARTOR, ID_CAZ, PROTECTIE_MARTOR, TIP_CITATIE)
VALUES (1,1,'NU','Fizic');

INSERT INTO MARTOR_CAZ (ID_MARTOR, ID_CAZ, PROTECTIE_MARTOR, TIP_CITATIE)
VALUES (2,1,'NU','Electronic');


INSERT INTO CAZ (ID_TRIBUNAL, TIP, DATA_I, DATA_F)
VALUES (2,'Civil', date '2020-01-12',date '2020-03-05');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (3,2, 'Persoana Vatamata');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (8,2, 'Suspect');

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT)
VALUES (3,2, 'Oficiu');

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (8,10, 'Ales',15000);

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (8,6, 'Ales',17000);

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (8,7, 'Ales',20000);

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (5,2,'Presedinte');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (1,2,'Membru');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (2,2,'Membru');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (1,2,'Presedinte Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (2,2,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (6,2,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (8,2,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (5,2,'Membru Complet');

INSERT INTO MARTOR_CAZ (ID_MARTOR, ID_CAZ, PROTECTIE_MARTOR, TIP_CITATIE)
VALUES (4,2,'DA','Fizic');

INSERT INTO MARTOR_CAZ (ID_MARTOR, ID_CAZ, PROTECTIE_MARTOR, TIP_CITATIE)
VALUES (5,2,'DA','Electronic');

INSERT INTO MARTOR_CAZ (ID_MARTOR, ID_CAZ, PROTECTIE_MARTOR, TIP_CITATIE)
VALUES (9,2,'DA','Electronic');


INSERT INTO CAZ (ID_TRIBUNAL, TIP, DATA_I, DATA_F)
VALUES (3,'Administrativ', date '2020-10-12',date '2022-01-05');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (4,3, 'Persoana Vatamata');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (5,3, 'Persoana Vatamata');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (6,3, 'Persoana Vatamata');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (9,3, 'Suspect');

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT)
VALUES (4,2, 'Oficiu');

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (5,9, 'Ales', 25000);

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (9,2, 'Ales',28000);

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (9,8, 'Ales',19000);

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (9,7, 'Ales',20000);

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (4,3,'Presedinte');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (6,3,'Membru');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (5,3,'Membru');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (5,3,'Presedinte Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (9,3,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (10,3,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (7,3,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (2,3,'Membru Complet');


INSERT INTO CAZ (ID_TRIBUNAL, TIP, DATA_I, DATA_F)
VALUES (2,'Penal', date '2019-04-17',date '2020-01-02');

INSERT INTO PARTICIPANT_CAZ(ID_PARTICIPANT, ID_CAZ, PARTE)
VALUES (10,4, 'Persoana Vatamata');

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (7,3, 'Ales',30000);

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (7,4, 'Ales',30000);

INSERT INTO PARTICIPANT_AVOCAT (ID_PARTICIPANT, ID_AVOCAT, TIP_AVOCAT, ONORARIUL)
VALUES (7,5, 'Ales',30000);

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (5,4,'Presedinte');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (3,4,'Membru');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (4,4,'Membru');

INSERT INTO PROCUROR_CAZ (ID_PROCUROR, ID_CAZ, FUNCTIE_PROCUROR)
VALUES (7,4,'Membru');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (3,4,'Presedinte Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (4,4,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (7,4,'Membru Complet');

INSERT INTO JUDECATOR_CAZ (ID_JUDECATOR, ID_CAZ, FUNCTIE_JUDECATOR)
VALUES (9,4,'Membru Complet');

INSERT INTO MARTOR_CAZ (ID_MARTOR, ID_CAZ, PROTECTIE_MARTOR, TIP_CITATIE)
VALUES (6,4,'DA','Fizic');

INSERT INTO MARTOR_CAZ (ID_MARTOR, ID_CAZ, PROTECTIE_MARTOR, TIP_CITATIE)
VALUES (7,4,'DA','Telefonic');

INSERT INTO MARTOR_CAZ (ID_MARTOR, ID_CAZ, PROTECTIE_MARTOR, TIP_CITATIE)
VALUES (8,4,'DA','Telefonic');

commit;